name: SuperSimpleSpawners
main: com.dumptruckman.supersimplespawners.SuperSimpleSpawners
version: maven-version-number
author: dumptruckman
commands:
    supersimplespawners:
        description: SuperSimpleSpawners
        usage: |
               /<command>
    sss:
        description: SuperSimpleSpawners
        usage: |
               /<command>
