name: SuperSimpleSpawners
main: com.dumptruckman.supersimplespawners.SuperSimpleSpawners
version: maven-version-number
author: dumptruckman

commands:
  supersimplespawnersreload:
    description: Reloads the config file for SuperSimpleSpawners.
    aliases: sssreload
    permission: sss.reload
    usage: /<command>
