name: SuperSimpleSpawners
main: com.dumptruckman.supersimplespawners.SuperSimpleSpawners
version: 1.1d
author: dumptruckman

permissions:
  supersimplespawners.*:
    description: 'Gives all permissions for this plugin'
    default: false
    children:
      supersimplespawners.place: true
      supersimplespawners.drop: true